package com.aquilamazzei.springhunter;

import com.aquilamazzei.springhunter.consts.AutoGenerateData;
import com.aquilamazzei.springhunter.services.TypeService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class SpringhunterApplication {

	public static void main(String[] args) {
		SpringApplication.run(SpringhunterApplication.class, args);
	}

}
