package com.aquilamazzei.springhunter.consts;


import com.aquilamazzei.springhunter.entities.*;
import com.aquilamazzei.springhunter.logics.Fight;
import com.aquilamazzei.springhunter.services.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.context.event.ApplicationReadyEvent;
import org.springframework.context.event.EventListener;
import org.springframework.stereotype.Component;


@Component
public class AutoGenerateData{

    @Autowired
    private WeaponService weapon;

    @Autowired
    private TypeService type;

    @Autowired
    private HeroClassService heroClass;

    @Autowired
    private HeroService hero;

    @Autowired
    private MonsterService monsterService;


    Player player = new Player("joca", "123");

    @EventListener(ApplicationReadyEvent.class)
    public void afterPropertiesSet(){

        Weapons weapons = new Weapons();
        for(Type item : weapons.typeList){
            System.out.println(item);
            type.insertType(item);
        }
        for(Weapon item : weapons.weaponsList){
             weapon.insertWeapon(item);
        }

        Classes classes = new Classes();
        for(HeroClass item : classes.heroClassesList)     {
            System.out.println(item);
        }

        Monsters monsters = new Monsters();
        for(Monster item : monsters.monstersList){
            monsterService.insertMonster(item);
        }

    }
}
