package com.aquilamazzei.springhunter.consts;


import com.aquilamazzei.springhunter.entities.*;
import com.aquilamazzei.springhunter.services.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.context.event.ApplicationReadyEvent;
import org.springframework.context.event.EventListener;
import org.springframework.stereotype.Component;


@Component
public class AutoGenerateData{

    @Autowired
    private WeaponService weapon;

    @Autowired
    private TypeService type;

    @Autowired
    private HeroClassService heroClass;

    @Autowired
    private HeroService hero;

    @Autowired
    private MonsterService monsterService;


    @EventListener(ApplicationReadyEvent.class)
    public void afterPropertiesSet(){
        Peon peon = new Peon();
        Player player = new Player("username", "123");
        Classes classes = new Classes();
        Arsenal arsenal = new Arsenal();
        Hero hero1 = new Hero(player, classes.heroClassesList.get(0),"Barbariana");

        Monster.dropWeapon(hero1);


        Monsters monsters = new Monsters();
        for(Monster item : monsters.monstersList){
            monsterService.insertMonster(item);
        }
    }
}
